services:
  postgres:
    container_name: postgres-sql-trailbuddy
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER:-trailbuddyuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-strongpassword}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${DB_NAME:-trailbuddy_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local