[build]
base = "."
command = """
    cd frontend &&
    mkdir -p src/environments &&
    echo "$ENVIRONMENT_PROD" > src/environments/environment.prod.ts &&
    npm install &&
    npm run build
  """
publish = "frontend/dist/frontend/browser"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
